### ISSUE TITLE
TODOs / roadmap

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#1054]
Things that would be great to finish by the end of the Photonics West conference in San Francisco at the end of January

![image](https://user-images.githubusercontent.com/4514346/209984019-35592a53-1e54-431b-8120-b9b5d7e9558c.png)

![image](https://user-images.githubusercontent.com/4514346/209988706-3ad5fbb6-7f15-457a-bed3-5aa3fdca1c28.png)

# Design

- [ ] Fix klayout backend and compare with gdstk #1031 
- [ ]  Serialize GDS files to YAML (preserving hierarchy)
- [x] Convert YAML netlist to spice #681 
- [x] Add generators for photonic components (taper,  bends, grating coupler, MMIs …)
- [x] Define test sequence for lab measurements (validation)
- [x] Fit simulations to build circuit models (coupler, waveguide …) #1055 
- [x] Extend simulators to support Analog design (spice) and RF quantum workflows. #681 
- [x] add non-manhattan router #1169 
- [ ] global router #57 
- [ ] schematic improvements #1176
- [x] #1177
- [ ] time domain? #1143 

# Verification

- [ ] LVS #934 
- [ ] Electrical and optical extraction, path length extractor.
- [ ] DFM Design for manufacturing. Simulate designs with erosion/dilation. Simulate devices after lithography (rounding effects)
- [ ] Yield estimation based on layout aware monte carlo simulations from erosion/dilation simulations

# Validation
- [ ] Data analysis flow. Extract device parameters from measurements.
- [ ] Webapp for comparing simulations and measurements (correlation database)
- [ ] Add example scripts and documentation for deploying and using the database #992 
- [x] #1178

# General 

- [ ] figure our recommended cloud deployment strategy. Smaller docker image?

@flaport 
@thomasdorch 
@SkandanC 
@simbilod 
@HelgeGehring 
@sebastian-goeldi
@Jan-David-Black 
@proppy
@mdecea 
@smartalech
@damienbonneau
@heitzmann
@xin-flex
@nikosavola 
@mithro
