### ISSUE TITLE
improve schematic driven layout

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/gdsfactory#931]
# TODO
- [ ] Demonstrate using visualizer to interactively refine layout placements, live
- [ ] Prettier display of nets and better control over waypoints

# Done
- [x] Implement symbols for components in schematic view
- [x] Allow rotation/mirroring in schematic placement

# Maybe:

- [ ] Compatibility with [signal Integrity](https://github.com/TeledyneLeCroy/SignalIntegrity) or SAX simulator

https://github.com/gdsfactory/gdsfactory/issues/516

**Comment by joamatab** [comment]
https://gdsfactory.github.io/gplugins/notebooks/20_schematic_driven_layout.html
